// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgodcbkimqzhdppaewqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnb2RjYmtpbXF6aGRwcGFld3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzU1NTQsImV4cCI6MjA3MzQxMTU1NH0.JcZ1v4ANLTk-UWkmhz6cJ7Bh5RdYy0fD1zjED2yOR5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});